name: Docker Image CI

on:
    push:
        branches: [ github-actions ]
    pull_request:
        branches: [ github-actions ]

env:
    DOCKER_IMAGE: tifennguillas/test-technique-angular

jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build testing image
              uses: docker/build-push-action@v2
              with:
                  tags: |
                      ${{ env.DOCKER_IMAGE }}
                  context: .
                  file: Dockerfile
                  load: true

            - name: Run tests
              run: |
                  docker run ${{ env.DOCKER_IMAGE }} bash -c 'yarn && ng test --no-watch'

    building:
        runs-on: ubuntu-latest
#        needs: [testing]
        if: ${{ github.event_name == 'push' }}
        steps:
            - name: Set env
              run: |
                  echo "RELEASE_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
            - uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build production image
              uses: docker/build-push-action@v2
              with:
                  tags: |
                      ${{ env.DOCKER_IMAGE }}:latest
                      ${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_VERSION }}
                  context: .
                  file: Dockerfile
                  load: true
                  build-args: |
                      APPLICATION_ENV=prod

            - name: Build dist
              run: |
                  docker run -v ${{ github.workspace }}/dist:/project/dist ${{ env.DOCKER_IMAGE }} bash -c 'ng build --prod'

            - name: Push production image
              uses: docker/build-push-action@v2
              with:
                  tags: |
                      ${{ env.DOCKER_IMAGE }}:latest
                      ${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_VERSION }}
                  push: true

            - name: GitHub Pages
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: dist/coding-test/
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
